### PR TITLE
added search icon

### PR DESCRIPTION
**Pull request by stevenmiller888**
@anthonyshort I added the search icon here. Can you check it out please?

### CODE REVIEW

**Comment by anthonyshort** [comment]
Is the image already in the sprite? If so, this is cool :)

**Comment by stevenmiller888** [comment]
Yes, I added it to each artboard :)

**Comment by anthonyshort** [comment]
Oh, I didn't see the sketch file. You'll need to output that to an SVG. I'll have a look

**Comment by stevenmiller888** [comment]
Ohh that makes sense. Just pushed it up with the SVGs

**Comment by anthonyshort** [comment]
I just updated everything. There were a couple of problems:

* The icon wasn't exactly 16px from the redshift icon. There's a 16x16 grid all the icons sit on.
* I added the redshift icon to all of them, so that the search icon is in the same x/y position in each image
* Updated the colours the match the brand colours (this is something I've been meaning to do :) )

**Comment by stevenmiller888** [comment]
Sweet man. Thanks for letting me know what the problems were! :)

**Pull request merged**
